# Generated by Django 3.1.2 on 2021-09-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210909_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag_word',
            field=models.TextField(default='random'),
        ),
    ]
