# Generated by Django 3.1.2 on 2021-09-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210909_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
